version: '3.8'

services:
  my-flask-app:
    build: .
    image: my-flask-app
    ports:
      - "4000:80"
    volumes:
      - ./db:/data
    environment:
      - DATABASE_URL=sqlite:////data/mydb.sqlite3
